dictionary = [
              'vaporwave',
              'aesthetic',
              '1999',
              'relax',
              'bedroom',
              'ecstasy',
              'nostalgic',
              'euphoric',
              'glue',
              'glow',
              'everything will be ok',
              'sleeping in',
              'meme',
              'you\'ve got mail',
              'regular scheduled programming',
              'nintendo',
              'dreamcast',
              'playstation',
              'nightdrive',
              'snick',
              'slowed',
              'japanese',
              'corporate',
              'wave',
              'nostalgia',
              'pizza',
              'tassoni',
              'pippo baudo',
              'italia',
              'sicilia',
              'cannolo',
              'powerglove',
              'lost cartridge',
              'infinite reverie',
              'new game',
              'aol',
              'ultra 64',
              'commodore',
              'vhs',
              'rgb split',
              'atari',
              'vcr',
              'remember summer days',
              'mallsoft',
              'the future is now',
              'crystal pepsi',
              'where am i',
              'im dreaming',
              'where are you going',
              'satisfaction guaranteed',
              'sciare'
]

alphabet = {
            "a":"ａ",
            "A":"Ａ",
            "b":"ｂ",
            "B":"Ｂ",
            "c":"ｃ",
            "C":"Ｃ",
            "d":"ｄ",
            "D":"Ｄ",
            "e":"ｅ",
            "E":"Ｅ",
            "f":"ｆ",
            "F":"Ｆ",
            "g":"ｇ",
            "G":"Ｇ",
            "h":"ｈ",
            "H":"Ｈ",
            "i":"ｉ",
            "I":"Ｉ",
            "j":"ｊ",
            "J":"Ｊ",
            "k":"ｋ",
            "K":"Ｋ",
            "l":"ｌ",
            "L":"Ｌ",
            "m":"ｍ",
            "M":"Ｍ",
            "n":"ｎ",
            "N":"Ｎ",
            "o":"ｏ",
            "O":"Ｏ",
            "p":"ｐ",
            "P":"Ｐ",
            "q":"ｑ",
            "Q":"Ｑ",
            "r":"ｒ",
            "R":"Ｒ",
            "s":"ｓ",
            "S":"Ｓ",
            "t":"ｔ",
            "T":"Ｔ",
            "u":"ｕ",
            "U":"Ｕ",
            "v":"ｖ",
            "V":"Ｖ",
            "w":"ｗ",
            "W":"Ｗ",
            "x":"ｘ",
            "X":"Ｘ",
            "y":"ｙ",
            "Y":"Ｙ",
            "z":"ｚ",
            "Z":"Ｚ"
}
