dictionary = [
    'vaporwave',
    'aesthetic',
    '1999',
    'relax',
    'bedroom',
    'ecstasy',
    'nostalgic',
    'euphoric',
    'glue',
    'glow',
    'rainbow as',
    'coloured with',
    'everything will be ok',
    'sleeping in',
    'meme',
    'you\'ve got mail',
    'regular scheduled programming',
    'nintendo',
    'dreamcast',
    'playstation',
    'nightdrive',
    'snick',
    'slowed',
    'japanese',
    'corporate',
    'wave',
    'nostalgia',
    'pizza',
    'tassoni',
    'pippo baudo',
    'italia',
    'sicilia',
    'cannolo',
    'powerglove',
    'lost cartridge',
    'infinite reverie',
    'new game',
    'aol',
    'ultra 64',
    'commodore',
    'vhs',
    'rgb split',
    'atari',
    'vcr',
    'remember summer days',
    'mallsoft',
    'the future is now',
    'crystal pepsi',
    'where am i',
    'im dreaming',
    'where are you going',
    'satisfaction guaranteed',
    'sciare'
]
